name: Test Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run make for basic example
      run: make build/solution_name.zip

    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
          name: project-test
          path: build/solution_name.zip
